version: '3'

services:
  api: # Node.js App
    container_name: mw-api
    build: .
    ports:
      - "3000:3000" # Expose API port
      - "9229:9229" # Expose Node process debug port (disable in production)
    environment: # Set ENV vars
     - NODE_ENV=local
     - ES_HOST=elasticsearch
     - PORT=3000
     - NODE_OPTIONS=--max-old-space-size=4096
    volumes: # Attach local data directory
      - ./malwords:/usr/src/app/malwords:ro
      - ./labels.json:/usr/src/app/labels.json:ro

  frontend: # Nginx Server For Frontend App
    container_name: mw-frontend
    image: nginx
    volumes: # Serve local "public" dir
      - ./public:/usr/share/nginx/html:ro
    ports:
      - "8080:80" # Forward site to localhost:8080

  elasticsearch: # Elasticsearch Instance
    container_name: mw-search
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.3
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data
    environment:
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
      - discovery.type=single-node
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"

volumes: # Define seperate volume for Elasticsearch data
  esdata:

